### ISSUE TITLE
Create an official container image for Cobbler

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2453]
### Is your feature request related to a problem?

Currently we only use Docker or containers in general for testing. Since it is apparently possible to run Cobbler in such an environment we should provide such a solution.

### The Behaviour you'd like

`docker pull cobbler` or something similar should pull a production ready Cobbler image.

### Alternatives you've considered

Well hosting in a VM is possible but not state of the art.

### Additional context

N/A

**Comment by SchoolGuy** [comment]
TODO List (incomplete currently):

- [ ] Creating all folders automatically. - #2860
- [x] Get templates for the folders from somewhere. - #3139
- [ ] Be able to restart remote services (dhcp, dns, ...) in a different container. - #3138
- [ ] Be able to configure everything via ENV variables. - #3137
- [ ] Provide docs how to use the container-stack with both Docker and Podman.
- [ ] Optional: Provide a way how to run it in Kubernetes.


For reference:

- `/srv/www/cobbler/links` only gets created during installation. Should also be created again with a `cobbler sync` if deleted manually.

**Comment by dansou901** [comment]
I can help with the Dockerfiles and configuration parsing once the creation of folders is implemented correctly. Maybe I can help also with Kubernetes when time comes.

**Comment by SchoolGuy** [comment]
To elaborate on this request a bit more:

- The desired architecture should follow the "one process per container" methodology. The missing technical points were mentioned above.
- The following issue will help us to put the Cobbler Daemon into a single container: https://github.com/cobbler/cobbler/issues/3234
- If multiple containers need to share data based on the filesystem (for example the tftpd with the Cobbler Daemon) then we should share a file mount.
- This should lead to a default stack of: Cobbler, DHCP, TFTP & Webserver Proxy

**Comment by SchoolGuy** [comment]
Update on this topic:

- For a few weeks we already have cobbler-tftp a replacement for the TFTP server.
- This means that the directory `/srv/tftpboot` or `/var/www/tftp` doesn't need to be persistent anymore.
- The Apache/Reverse Proxy Process can be moved to a dedicated container.
- The HTTP API can also be reverse-proxied as it is accessing the XML-RPC API via the network. (It needs access to the settings file of Cobbler.)
- The Cobbler process itself can run in foreground mode.

There will need to be container-specific tweaks but a one-process-per-container setup could now be doable.

It won't be a pleasant experience though since the config cannot be easily managed and the CLI is not yet remotely usable. The standalone Golang CLI is on its way to completion though. The remaining above-mentioned topics are also not solved making this experience a bit odd per-default.

**Comment by SchoolGuy** [comment]
To restart the docker container for DHCP and DNS we can use the project [watchdog](https://pypi.org/project/watchdog/)  to watch the configs and connect the Docker API to restart the container. This should be a fairly small script. Of course the desired alternative is to restart the container directly from Cobbler via the Python API (https://stackoverflow.com/a/73897635).
