### ISSUE TITLE
[docs] Collection of errors in the documentation

### ISSUE THREAD

**Issue by nodeg** [cobbler/cobbler#2593]
This issue is for collecting all errors regarding documentation.

### TODO
- [x] Fix broken links
- [x] Add new `cobbler sync --dns` and `cobbler sync --dhcp` commands
- [x] Improve the [source installation section](https://cobbler.readthedocs.io/en/latest/installation-guide.html#id2)
- [x] Add missing ISC manager module
- [x] Fix links in `/etc/cobbler/modules.conf`
- [x] Remove whitespaces in several non Python files
- [x] Update DNS [user guide](https://cobbler.readthedocs.io/en/latest/user-guide.html#dns-configuration-management)
- [x] Adjust [`cobbler report`](https://cobbler.readthedocs.io/en/latest/cobbler.html#cobbler-report). There is no `--name` option.
- [x] ~~Remove [Kickstart validation](https://cobbler.readthedocs.io/en/latest/user-guide.html?highlight=validateks#kickstart-validation)~~ was renamed to autoinstall validation
- [x] Extend the power management section and move to dedicated page. The content of the old Markdown Wiki should be restored.

#### Source installation

The `ExecStart` in `/etc/cobbler/cobblerd.service` has to be adjusted differently on different distros since the `cobblerd` binary resides in different locations after a `make install`.
- Leap 15.3: `/usr/bin/cobblerd` is fine
- Tumbleweed: `/usr/local/bin/cobblerd`

#### Fix broken links
There are several broken links in our documentation which need to be adjusted to our `.rst` format. Some of them can be removed since they point to entries that no longer exists.

Here are a few examples: 

[![https://imgur.com/qo2iH3F.png](https://imgur.com/qo2iH3F.png)](https://imgur.com/qo2iH3F.png)
[![https://imgur.com/rA77Voj.png](https://imgur.com/rA77Voj.png)](https://imgur.com/rA77Voj.png)
[![https://imgur.com/VfHZhNX.png](https://imgur.com/VfHZhNX.png)](https://imgur.com/VfHZhNX.png)

**Comment by SchoolGuy** [comment]
Things that are required additionally:

- [ ] Get rid of `modules.conf` mentions
- [ ] Upgrade HTTP links to HTTPS
